# Excel文件名到JSON文件名的映射
[file_mappings]
"C.车" = "base_car"  # 将 C.车.xlsx 的输出改为 base_car.json
"Z.资源" = "base_res"
"P.皮肤角色" = "base_skin_juese"
"P.皮肤巨龙" = "base_skin_long"
"P.皮肤炮台" = "base_skin_pao"
"P.皮肤盒子" = "base_skin_box"
"J.角色升级" = "base_juese_lv"
"P.炮塔" = "base_pao"
"G.关卡" = "base_level"
"C.宠物龙" = "base_pet"
"Y.语言-错误码" = "base_lang_errcode"
"Y.语言-文本" = "base_lang_text"
"C.常量表" = "base_constant"






